Check monad: support for accumulated errors
Ignore-this: 6ac522f8427e6ec64cc2e1e94dab5199
In addition to warnings, the Check monad in GF.Infra.CheckM can now accumulate
errors. There are two new functions

	checkAccumError: Message -> Check ()
	accumulateError :: (a -> Check a) -> a -> Check a

The former (with the same type as checkWarn) is used to report an accumulated
(nonfatal) error. The latter converts fatal errors into accumulated errors.

Accumulated errors are reported as regular errors by runCheck.

Also, the Check monad type has been made abstract.

darcs-hash:20120625140158-bae10-dc4d73d48f68463ca8091b5141726f52201786e6.gz