Setup.hs: switch to base-4 exceptions
Ignore-this: a5f519a573acfe6bdf8cea7065a21887

Fixes build failure on ghc-7.6:
    $ runhaskell Setup.hs configure
    Setup.hs:394:14: Not in scope: `E.try'

base-4 is available/default since ghc-6.10.

darcs-hash:20130309211803-6895e-9281a967e74db55f793b9cfe0cbb69015216b9ab.gz