minibar: fix bug introduced in previous update
Ignore-this: 762539b8de0bad15dd9923fad348858
It could case JavaScript error

	ReferenceError: initial_grammar is not defined

darcs-hash:20121121190152-bae10-bb3a1c0337ed97f6d706e529ad65e7bb4cec704d.gz